<?php

$categories = [
    2 => ['Kiến thức công nghệ', 'Technology Knowledge', 'ket-noi-wifi-esim.jpg'],
    5 => ['Hướng dẫn', 'Guides', 'huong-dan-bao-mat-va-chuyen-du-lieu.jpg'],
    6 => ['Giải pháp', 'Solutions', 'giai-phap-zero-trust-crm.jpg'],
    7 => ['Lập trình', 'Programming', 'lap-trinh-typescript-ci.jpg'],
    8 => ['Hệ điều hành', 'Operating Systems', 'he-dieu-hanh-khoi-phuc-dual-boot.jpg'],
];

$items = [
[
'file'=>'wifi-7-la-gi.html','cat'=>2,
'vi'=>['Wi-Fi 7 là gì? Khi nào nên nâng cấp router và thiết bị?','wifi-7-la-gi','Wi-Fi 7, 802.11be, MLO, 6 GHz, router','Hiểu các điểm mới của Wi-Fi 7 và cách quyết định có nên nâng cấp router, thiết bị hay đường truyền.','Wi-Fi 7 không chỉ tăng tốc độ tối đa. Chuẩn 802.11be còn hướng tới độ trễ thấp và kết nối ổn định hơn trong môi trường có nhiều thiết bị.','Điểm mới quan trọng','Kênh 320 MHz tăng băng thông trên dải 6 GHz ở thị trường cho phép. Multi-Link Operation có thể phối hợp nhiều liên kết, 4K-QAM mang nhiều dữ liệu hơn khi tín hiệu tốt, còn Multi-RU sử dụng phổ linh hoạt hơn.','Khi nào đáng nâng cấp?','Nên cân nhắc khi truyền tệp nội bộ lớn, dùng Internet đa gigabit, chơi game hoặc stream nhạy với độ trễ và đã có nhiều máy khách tương thích. Với đường truyền dưới 1 Gbps, tối ưu vị trí router hoặc thêm access point thường đáng tiền hơn.','Checklist mua router','Kiểm tra khả năng dùng 6 GHz, tốc độ cổng WAN/LAN, WPA3, thời gian cập nhật bảo mật và vùng phủ thực tế. Thiết bị Wi-Fi cũ vẫn kết nối được nhưng không nhận toàn bộ lợi ích của Wi-Fi 7.','https://www.wi-fi.org/discover-wi-fi/wi-fi-certified-7'],
'en'=>['What Is Wi-Fi 7, and When Should You Upgrade?','what-is-wifi-7-when-to-upgrade','Wi-Fi 7, 802.11be, MLO, 6 GHz, router','Understand Wi-Fi 7 improvements and decide whether your router, client devices, and internet plan justify an upgrade.','Wi-Fi 7 is about more than peak speed. The 802.11be standard also targets lower latency and more dependable connections in busy environments.','Important improvements','320 MHz channels increase bandwidth in the 6 GHz band where permitted. Multi-Link Operation coordinates links, 4K-QAM carries more data with a strong signal, and Multi-RU uses spectrum more flexibly.','When is an upgrade worthwhile?','Consider it for large local transfers, multi-gigabit internet, latency-sensitive gaming or streaming, and many compatible clients. With sub-gigabit service, better router placement or another access point may provide more value.','Router checklist','Check local 6 GHz availability, WAN and LAN port speeds, WPA3, the security-support period, and real coverage. Older clients remain compatible but cannot use every Wi-Fi 7 feature.','https://www.wi-fi.org/discover-wi-fi/wi-fi-certified-7']],
[
'file'=>'esim-la-gi.html','cat'=>2,
'vi'=>['eSIM là gì? Ưu điểm, giới hạn và lưu ý khi đổi điện thoại','esim-la-gi','eSIM là gì, SIM điện tử, chuyển eSIM, dual SIM','Tìm hiểu cách eSIM hoạt động, ưu nhược điểm và checklist an toàn khi đổi điện thoại hoặc nhà mạng.','eSIM là hồ sơ thuê bao được tải vào phần cứng bảo mật trong thiết bị, cho phép kích hoạt mạng di động mà không lắp thẻ SIM vật lý.','Cách eSIM hoạt động','Nhà mạng cung cấp mã QR, ứng dụng hoặc quy trình chuyển trực tiếp để tải hồ sơ. Thiết bị có thể lưu nhiều hồ sơ, nhưng số đường dây hoạt động cùng lúc phụ thuộc phần cứng và nhà mạng.','Lợi ích và giới hạn','eSIM thuận tiện khi dùng hai số hoặc mua gói dữ liệu du lịch. Tuy nhiên, khả năng hỗ trợ khác nhau theo máy, quốc gia và nhà mạng; chuyển máy có thể cần Internet, xác minh danh tính hoặc hỗ trợ kỹ thuật.','Trước khi đổi máy','Xác nhận máy mới tương thích, giữ phương thức xác minh dự phòng và không xóa eSIM trên máy cũ trước khi máy mới có sóng. Chỉ đặt lại máy cũ sau khi cuộc gọi, SMS và dữ liệu hoạt động bình thường.','https://support.apple.com/en-us/118669'],
'en'=>['What Is an eSIM? Benefits, Limits, and Migration Tips','what-is-esim-benefits-limits-migration','what is eSIM, electronic SIM, transfer eSIM, dual SIM','Learn how eSIM works, its benefits and limitations, and how to migrate safely when changing phones or carriers.','An eSIM is a carrier profile downloaded to secure hardware in a device, enabling cellular service without inserting a physical SIM card.','How eSIM works','A carrier provides a QR code, app, or direct-transfer flow. A device may store several profiles, although the number of simultaneously active lines depends on hardware and carrier support.','Benefits and limits','eSIM is convenient for dual numbers and travel data. Support still varies by device, country, and carrier, and migration may require connectivity, identity checks, or support assistance.','Before changing phones','Confirm compatibility, retain a backup verification method, and do not erase the old profile until the new phone has service. Reset the old phone only after calls, messages, and data work.','https://support.apple.com/en-us/118669']],
[
'file'=>'bao-mat-wifi-gia-dinh.html','cat'=>5,
'vi'=>['Hướng dẫn bảo mật Wi-Fi gia đình: 10 bước nên làm ngay','bao-mat-wifi-gia-dinh','bảo mật Wi-Fi, router gia đình, WPA3, mạng khách','Checklist thiết lập router gia đình an toàn bằng cập nhật, WPA3, mạng khách và giám sát thiết bị.','Router là cửa ngõ của mạng gia đình. Cấu hình mặc định yếu có thể ảnh hưởng máy tính, điện thoại, camera và thiết bị thông minh.','Bảo vệ phần quản trị','Cập nhật firmware, bật cập nhật tự động, đổi mật khẩu quản trị và tắt quản trị từ Internet nếu không cần. Không dùng chung mật khẩu quản trị với mật khẩu Wi-Fi.','Thiết lập Wi-Fi','Dùng WPA3 hoặc WPA2-AES, đặt mật khẩu dài và duy nhất, tắt WPS khi không dùng. Tạo mạng khách cho khách và thiết bị IoT để giảm phạm vi ảnh hưởng nếu một thiết bị bị xâm nhập.','Kiểm tra định kỳ','Xem danh sách thiết bị kết nối, xóa thiết bị lạ và thay router đã hết hỗ trợ. Nếu nghi bị xâm nhập, cập nhật, đổi thông tin đăng nhập, kiểm tra DNS hoặc đặt lại và cấu hình thủ công.','https://consumer.ftc.gov/articles/how-secure-your-home-wi-fi-network'],
'en'=>['How to Secure Your Home Wi-Fi: 10 Steps to Take Now','how-to-secure-home-wifi','secure home Wi-Fi, router, WPA3, guest network','A practical home-router checklist covering updates, WPA3, guest networks, admin access, and device reviews.','Your router is the gateway to the home network. Weak defaults can affect computers, phones, cameras, and connected devices.','Protect administration','Update firmware, enable automatic updates, change the admin password, and disable internet-facing administration unless required. Keep admin and Wi-Fi passwords separate.','Configure Wi-Fi','Use WPA3 or WPA2-AES, choose a long unique passphrase, and disable unused WPS. Put visitors and IoT devices on a guest network to reduce the impact of a compromised device.','Review regularly','Inspect connected devices, remove unknown entries, and replace unsupported routers. After suspected compromise, update, rotate credentials, inspect DNS, or factory-reset and configure manually.','https://consumer.ftc.gov/articles/how-secure-your-home-wi-fi-network']],
[
'file'=>'chuyen-du-lieu-sang-dien-thoai-moi.html','cat'=>5,
'vi'=>['Hướng dẫn chuyển dữ liệu sang điện thoại mới an toàn và đầy đủ','chuyen-du-lieu-sang-dien-thoai-moi','chuyển dữ liệu điện thoại, đổi điện thoại, sao lưu, eSIM','Quy trình chuyển ảnh, tài khoản, ứng dụng và eSIM, rồi kiểm tra đầy đủ trước khi xóa máy cũ.','Chuyển máy không kết thúc khi ảnh và danh bạ xuất hiện. Tài khoản xác thực, eSIM, ứng dụng ngân hàng và lịch sử trò chuyện cũng cần được kiểm tra.','Chuẩn bị','Cập nhật và sạc hai máy, tạo bản sao lưu mới, kiểm tra dung lượng đám mây và ghi lại ứng dụng xác thực cùng mã khôi phục. Chưa đặt lại máy cũ.','Thực hiện chuyển','Ưu tiên công cụ chính thức của hệ điều hành và dùng cáp khi dữ liệu lớn. Giữ hai máy gần nhau, cùng mạng và đọc kỹ cảnh báo về nội dung không được hỗ trợ.','Xác minh trước khi xóa','Kiểm tra cuộc gọi, SMS, ảnh, ghi chú, ứng dụng chat, 2FA, eSIM, ngân hàng và thiết bị đeo. Dùng máy mới vài ngày, tạo thêm bản sao lưu rồi mới đăng xuất và đặt lại máy cũ.','https://support.google.com/android/answer/6193424'],
'en'=>['How to Transfer Data to a New Phone Safely and Completely','transfer-data-to-new-phone-safely','phone data transfer, switch phones, backup, eSIM','Transfer photos, accounts, apps, and eSIM, then verify everything before erasing the old phone.','Migration is not complete when photos and contacts appear. Authentication accounts, eSIM, banking apps, and chat history also require verification.','Prepare','Update and charge both phones, create a fresh backup, check cloud capacity, and inventory authenticators and recovery codes. Do not reset the old phone.','Run the transfer','Prefer the operating system vendor’s migration tool and use a cable for large datasets. Keep devices close and on the same network, and read unsupported-data warnings.','Verify before erasing','Check calls, messages, photos, notes, chats, 2FA, eSIM, banking, and wearables. Use the new phone for several days and create another backup before signing out and resetting the old one.','https://support.google.com/android/answer/6193424']],
[
'file'=>'zero-trust-cho-doanh-nghiep-nho.html','cat'=>6,
'vi'=>['Zero Trust cho doanh nghiệp nhỏ: Lộ trình triển khai thực tế','zero-trust-cho-doanh-nghiep-nho','Zero Trust, MFA, bảo mật doanh nghiệp nhỏ, quyền tối thiểu','Lộ trình Zero Trust thực tế tập trung vào danh tính, thiết bị, phân quyền, phân đoạn và giám sát.','Zero Trust không phải một sản phẩm. Đó là cách liên tục xác minh người dùng, thiết bị và ngữ cảnh trước khi cấp quyền truy cập tài nguyên.','Ba nguyên tắc','Xác minh rõ ràng bằng nhiều tín hiệu, cấp quyền tối thiểu có thời hạn và giả định sự cố đã xảy ra để giới hạn phạm vi ảnh hưởng.','Lộ trình triển khai','Kiểm kê tài khoản, thiết bị và dữ liệu; bật MFA chống phishing; chuẩn hóa cập nhật và mã hóa; sau đó phân đoạn hệ thống, tập trung log và diễn tập thu hồi quyền.','Đo lường tiến độ','Theo dõi tỷ lệ MFA, thiết bị được quản lý, tài khoản đặc quyền, thời gian thu hồi quyền và ứng dụng có log tập trung. Bắt đầu từ quản trị viên, email, VPN và dữ liệu khách hàng.','https://csrc.nist.gov/pubs/sp/800/207/final'],
'en'=>['Zero Trust for Small Businesses: A Practical Roadmap','zero-trust-for-small-businesses','Zero Trust, MFA, small business security, least privilege','A practical Zero Trust roadmap focused on identities, devices, least privilege, segmentation, and monitoring.','Zero Trust is not one product. It is the practice of continuously evaluating users, devices, and context before granting access to resources.','Three principles','Verify explicitly with multiple signals, grant time-limited least privilege, and assume breach so the potential impact stays contained.','Implementation roadmap','Inventory identities, devices, and data; enable phishing-resistant MFA; standardize updates and encryption; then segment systems, centralize logs, and rehearse access revocation.','Measure progress','Track MFA coverage, managed devices, privileged accounts, revocation time, and applications with centralized logging. Start with administrators, email, VPN, and customer data.','https://csrc.nist.gov/pubs/sp/800/207/final']],
[
'file'=>'chon-crm-cho-doanh-nghiep.html','cat'=>6,
'vi'=>['Cách chọn CRM phù hợp mà không lãng phí ngân sách','chon-crm-cho-doanh-nghiep','chọn CRM, CRM doanh nghiệp, triển khai CRM, TCO','Khung đánh giá CRM theo quy trình, dữ liệu, tích hợp, khả năng sử dụng và tổng chi phí sở hữu.','CRM tốt nhất không phải hệ thống nhiều tính năng nhất, mà là hệ thống đội ngũ sử dụng đều đặn để tạo dữ liệu tin cậy và hành động tiếp theo rõ ràng.','Bắt đầu từ quy trình','Vẽ hành trình từ khách tiềm năng đến hợp đồng và chăm sóc sau bán. Xác định dữ liệu bắt buộc, người chịu trách nhiệm, điểm bàn giao và báo cáo trước khi xem demo.','Lập ma trận đánh giá','Chấm điểm mức phù hợp quy trình, trải nghiệm di động, tích hợp, API, phân quyền, nhật ký, xuất dữ liệu và tổng chi phí gồm giấy phép, triển khai, đào tạo, vận hành.','Thử nghiệm trước khi mua','Dùng một nhóm nhỏ và pipeline thật trong 4-6 tuần. Đo tỷ lệ nhập dữ liệu, thời gian cập nhật, cơ hội bị bỏ quên và chất lượng dự báo. Tránh tùy biến sâu trước khi hiểu quy trình chuẩn.','https://www.nist.gov/system/files/documents/2019/10/17/nist_choosing_a_vendor.pdf'],
'en'=>['How to Choose the Right CRM Without Wasting Budget','how-to-choose-the-right-crm','choose CRM, business CRM, CRM implementation, TCO','Evaluate CRM options by workflow, data, integrations, adoption, security, and total cost before committing.','The best CRM is not the one with the longest feature list; it is the system a team consistently uses to create trustworthy data and clear next actions.','Start with the process','Map the journey from lead to contract and after-sales care. Define required data, ownership, handoffs, and reports before product demonstrations.','Build an evaluation matrix','Score workflow fit, mobile use, integrations, APIs, permissions, audit logs, export, and total cost across licensing, implementation, training, and operations.','Pilot before buying','Use a small team and a real pipeline for four to six weeks. Measure data completion, update time, neglected opportunities, and forecast quality. Avoid deep customization before learning the standard process.','https://www.nist.gov/system/files/documents/2019/10/17/nist_choosing_a_vendor.pdf']],
[
'file'=>'typescript-strict-mode.html','cat'=>7,
'vi'=>['TypeScript strict mode: Tăng an toàn mà không làm vỡ dự án','typescript-strict-mode','TypeScript strict, strictNullChecks, noImplicitAny, migrate','Lộ trình bật TypeScript strict mode từng bước, xử lý null, unknown và ngăn phát sinh nợ kiểu dữ liệu.','Strict mode giúp TypeScript tìm nhiều lỗi trước khi chạy, nhưng bật toàn bộ trên dự án cũ có thể tạo hàng nghìn cảnh báo cần một chiến lược di chuyển.','strict gồm những gì?','Tùy chọn strict bật một nhóm kiểm tra như noImplicitAny, strictNullChecks và strictFunctionTypes. Nhóm này có thể thay đổi theo phiên bản, vì vậy nên cố định TypeScript trong dự án.','Lộ trình di chuyển','Chạy typecheck riêng trong CI, bật từng cờ, sửa theo module và ngăn mã mới tạo thêm lỗi. Dùng unknown cho dữ liệu chưa tin cậy rồi thu hẹp bằng kiểm tra runtime.','Điều nên tránh','any, toán tử non-null và ép kiểu kép có thể làm cảnh báo biến mất nhưng không làm mã an toàn. Với thư viện thiếu kiểu, hãy bổ sung khai báo nhỏ, kiểm chứng đầu vào hoặc nâng cấp.','https://www.typescriptlang.org/tsconfig/strict.html'],
'en'=>['TypeScript Strict Mode: Improve Safety Without Breaking the Project','typescript-strict-mode-migration','TypeScript strict, strictNullChecks, noImplicitAny, migration','A staged TypeScript strict-mode migration covering nulls, unknown data, CI, and preventing new type debt.','Strict mode finds more defects before runtime, but enabling every check in a mature project may reveal thousands of issues that need a migration strategy.','What does strict include?','The strict option enables checks such as noImplicitAny, strictNullChecks, and strictFunctionTypes. The group may evolve, so pin the project TypeScript version.','Migration path','Run type checking separately in CI, enable flags incrementally, fix one module at a time, and prevent new debt. Represent untrusted data as unknown and narrow it with runtime checks.','What to avoid','any, non-null assertions, and double casts can silence diagnostics without making code safer. For weak library types, add a small declaration, validate input, or upgrade.','https://www.typescriptlang.org/tsconfig/strict.html']],
[
'file'=>'github-actions-ci-nodejs.html','cat'=>7,
'vi'=>['Thiết lập CI cho dự án Node.js với GitHub Actions','github-actions-ci-nodejs','GitHub Actions Node.js, Node CI, npm ci, test','Xây dựng pipeline Node.js có cài đặt tái lập, cache, lint, test, build và bảo vệ pull request.','Pipeline CI tốt phải tái lập môi trường sạch và nhanh chóng trả lời rằng thay đổi có vượt qua lint, kiểu dữ liệu, kiểm thử và build hay không.','Các bước tối thiểu','Workflow cần checkout mã, setup-node với phiên bản cố định, cache kho tải npm, chạy npm ci rồi lint, typecheck, test và build. npm ci cài đúng lockfile và thất bại nếu manifest lệch.','Mở rộng hợp lý','Dùng matrix khi hỗ trợ nhiều phiên bản Node, tách job khi cần chạy song song, upload báo cáo khi lỗi, đặt timeout và hủy lượt cũ của cùng pull request.','Bảo mật workflow','Giới hạn quyền token, khóa phiên bản action đáng tin cậy và không đưa bí mật cho mã pull request không tin cậy. Chỉ deploy sau khi toàn bộ kiểm tra bắt buộc đã qua.','https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs'],
'en'=>['Set Up Node.js CI with GitHub Actions','set-up-nodejs-ci-github-actions','GitHub Actions Node.js, Node CI, npm ci, testing','Build a Node.js pipeline with reproducible installs, caching, lint, tests, builds, and pull-request protection.','A useful CI pipeline recreates a clean environment and quickly shows whether a change passes linting, type checks, tests, and the production build.','Minimum steps','Checkout the code, use setup-node with a pinned version, cache the npm download store, run npm ci, then lint, typecheck, test, and build. npm ci follows the lockfile and fails on manifest drift.','Expand carefully','Use a matrix for supported Node versions, split jobs for useful parallelism, upload reports on failure, add timeouts, and cancel obsolete runs for the same pull request.','Workflow security','Minimize token permissions, pin trusted actions, and never expose secrets to untrusted pull-request code. Deploy only after required checks pass.','https://docs.github.com/en/actions/use-cases-and-examples/building-and-testing/building-and-testing-nodejs']],
[
'file'=>'khoi-phuc-windows-11.html','cat'=>8,
'vi'=>['Các tùy chọn khôi phục Windows 11: Nên dùng cách nào?','khoi-phuc-windows-11','khôi phục Windows 11, System Restore, Reset this PC, Windows RE','Phân biệt các công cụ khôi phục Windows 11 để chọn phương án ít mất dữ liệu nhất.','Windows 11 có nhiều công cụ khôi phục với mức tác động khác nhau. Chọn đúng thứ tự giúp sửa lỗi mà không vội xóa ứng dụng hoặc dữ liệu.','Chọn theo triệu chứng','Không khởi động sau thay đổi: thử Startup Repair hoặc gỡ cập nhật. Lỗi sau driver/phần mềm: System Restore. Hỏng kéo dài: Reset this PC. Ổ mới hoặc lỗi nặng: recovery drive hoặc cài sạch.','Chuẩn bị trước','Sao lưu tệp, lưu khóa BitLocker, ghi lại tài khoản và giấy phép, đồng thời rút thiết bị ngoại vi không cần thiết. Keep my files vẫn gỡ ứng dụng và không thay thế bản sao lưu.','Sau khi khôi phục','Cập nhật Windows và driver, kiểm tra Device Manager, bật lại bảo vệ hệ thống và tạo bản sao lưu. Nếu lỗi lặp lại, kiểm tra ổ đĩa và bộ nhớ thay vì tiếp tục đặt lại.','https://support.microsoft.com/en-us/windows/recovery-options-in-windows-31ce2444-7de3-818c-d626-e3b5a3024da5'],
'en'=>['Windows 11 Recovery Options: Which One Should You Use?','windows-11-recovery-options','Windows 11 recovery, System Restore, Reset this PC, Windows RE','Compare Windows 11 recovery tools and choose the least destructive option for each failure.','Windows 11 offers recovery tools with very different impact. Choosing the right order may fix a problem without immediately removing applications or data.','Choose by symptom','After a boot-breaking change, try Startup Repair or uninstalling an update. For driver or app trouble, use System Restore. Persistent corruption may need Reset this PC; a new disk or severe failure may require recovery media.','Prepare first','Back up files, save the BitLocker key, inventory accounts and licenses, and disconnect unnecessary peripherals. Keep my files still removes apps and does not replace a backup.','After recovery','Update Windows and drivers, inspect Device Manager, enable system protection, and create a backup. Repeated failures call for storage and memory diagnostics rather than another reset.','https://support.microsoft.com/en-us/windows/recovery-options-in-windows-31ce2444-7de3-818c-d626-e3b5a3024da5']],
[
'file'=>'dual-boot-ubuntu-windows.html','cat'=>8,
'vi'=>['Dual boot Ubuntu và Windows: Chuẩn bị và cài đặt an toàn','dual-boot-ubuntu-windows','dual boot Ubuntu Windows, UEFI, BitLocker, phân vùng','Chuẩn bị sao lưu, BitLocker, UEFI và phân vùng trước khi cài Ubuntu cạnh Windows.','Dual boot cho hiệu năng gốc của Ubuntu và Windows, nhưng thay đổi phân vùng và mã hóa cần được chuẩn bị kỹ để tránh mất dữ liệu hoặc lỗi khởi động.','Trước khi thay đổi ổ đĩa','Sao lưu, tạo USB khôi phục Windows, lưu khóa BitLocker và kiểm tra UEFI. Thu nhỏ phân vùng bằng Disk Management rồi để vùng trống chưa định dạng cho Ubuntu.','Thử trước khi cài','Tải ISO từ Ubuntu và tạo USB khởi động. Dùng Try Ubuntu để kiểm tra Wi-Fi, âm thanh, đồ họa, bàn phím và touchpad. Khởi động USB cùng chế độ UEFI với Windows.','Cài đặt và xác minh','Chọn cài cạnh Windows khi hệ thống được nhận đúng. Nếu chia thủ công, không format phân vùng EFI hiện có. Sau khi cài, khởi động thử cả hai hệ điều hành, cập nhật và chỉ bật lại BitLocker khi boot ổn định.','https://ubuntu.com/tutorials/install-ubuntu-desktop'],
'en'=>['Dual Boot Ubuntu and Windows: Prepare and Install Safely','dual-boot-ubuntu-windows-safely','dual boot Ubuntu Windows, UEFI, BitLocker, partitions','Prepare backups, BitLocker, UEFI, and disk partitions before installing Ubuntu alongside Windows.','Dual boot provides native Ubuntu and Windows performance, but partitioning and encryption changes require preparation to prevent data loss or boot failure.','Before changing the disk','Back up data, create Windows recovery media, save the BitLocker key, and confirm UEFI mode. Shrink Windows in Disk Management and leave unallocated space for Ubuntu.','Test before installation','Download the ISO from Ubuntu and create bootable media. Use Try Ubuntu to test Wi-Fi, audio, graphics, keyboard, and touchpad. Boot the USB in the same UEFI mode as Windows.','Install and verify','Choose installation alongside Windows when detection is correct. For manual partitioning, do not format the existing EFI partition. After installation, boot both systems, update them, and resume BitLocker only when boot is stable.','https://ubuntu.com/tutorials/install-ubuntu-desktop']],
];

$out = [];
foreach ($items as $item) {
    [$categoryVi, $categoryEn, $image] = $categories[$item['cat']];
    foreach (['vi', 'en'] as $locale) {
        $d = $item[$locale];
        $body = '<p><strong>'.htmlspecialchars($d[4], ENT_QUOTES | ENT_HTML5, 'UTF-8').'</strong></p>';
        for ($i = 5; $i <= 10; $i += 2) {
            $body .= '<h2>'.htmlspecialchars($d[$i], ENT_QUOTES | ENT_HTML5, 'UTF-8').'</h2><p>'.htmlspecialchars($d[$i + 1], ENT_QUOTES | ENT_HTML5, 'UTF-8').'</p>';
        }
        $body .= '<h2>'.($locale === 'vi' ? 'Nguồn tham khảo' : 'Reference').'</h2><ul><li><a href="'.htmlspecialchars($d[11], ENT_QUOTES | ENT_HTML5, 'UTF-8').'" target="_blank" rel="noopener noreferrer">'.parse_url($d[11], PHP_URL_HOST).'</a></li></ul>';
        $out[$item['file']][$locale] = [
            'title' => $d[0], 'slug' => $d[1], 'image' => $image,
            'category_vi' => $categoryVi, 'category_en' => $categoryEn,
            'meta_title' => $d[0], 'meta_keywords' => $d[2],
            'meta_description' => $d[3], 'tags' => array_map('trim', explode(',', $d[2])),
            'body' => $body,
        ];
    }
}
return $out;

